version: "3.7"

services:
  db:
    image: mariadb:10.5.8
    container_name: challenge_db
    environment:
      - MYSQL_ROOT_PASSWORD=testpass
      - MYSQL_DATABASE=challenge
    volumes:
      - devmysqldb:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d

  backend:
    build: backend-python
    container_name: challenge_backend
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend-python:/app
    stdin_open: true # enable attach for pdb
    tty: true
    ports:
      - "8080:80"

  site:
    build: frontend-react
    container_name: challenge_site
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend-react:/site
    ports:
      - "8090:80"

  adminer:
    image: adminer
    container_name: challenge_db_adminer
    restart: always
    ports:
      - 8888:8080

volumes:
  devmysqldb:
